Extensible = {
  *text => any
}

Command = {
  id: uint,
  CommandData,
  Extensible,
}

CommandData = (
  SessionCommand //
  VendorSettingsCommand //
  InteractionCommand
)

EmptyParams = { Extensible }

SessionCommand = (SessionNewCommand)

CapabilitiesRequest = {
  ?atName: text,
  ?atVersion: text,
  ?platformName: text,
  Extensible,
}

SessionNewCommand = {
  method: "session.new",
  params: {capabilities: CapabilitiesRequestParameters},
}

CapabilitiesRequestParameters = {
  ?alwaysMatch: CapabilitiesRequest,
}

VendorSettingsCommand = {
  VendorSettingsSetSettingsCommand //
  VendorSettingsGetSettingsCommand //
  VendorSettingsGetSupportedSettingsCommand
}

VendorSettingsSetSettingsCommand = {
  method: "<vendor>:settings.setSettings",
  params: VendorSettingsSetSettingsParameters
}

VendorSettingsSetSettingsParameters = {
  settings: [1* VendorSettingsSetSettingsParametersItem ],
}

VendorSettingsSetSettingsParametersItem = {
  name: text,
  value: any,
  Extensible,
}

VendorSettingsGetSettingsCommand = {
  method: "<vendor>:settings.getSettings",
  params: VendorSettingsGetSettingsParameters
}

VendorSettingsGetSettingsParameters = {
  settings: [1* VendorSettingsGetSettingsParametersItem ],
}

VendorSettingsGetSettingsParametersItem = {
  name: text,
  Extensible,
}

VendorSettingsGetSupportedSettingsCommand = {
  method: "<vendor>:settings.getSupportedSettings",
  params: EmptyParams
}

InteractionCommand = (InteractionPressKeysCommand)

InteractionPressKeysCommand = {
  method: "interaction.pressKeys",
  params: InteractionPressKeysParameters
}

InteractionPressKeysParameters = {
  "keys" => KeyCombination,
  Extensible,
}

KeyCombination = [
  1* text
]
